# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20171119_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachaprofile',
            name='notes',
            field=models.FileField(upload_to=b''),
        ),
    ]
